# Generated by Django 2.0.2 on 2018-02-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomActiu', models.CharField(max_length=50)),
                ('descripcio', models.CharField(max_length=200)),
                ('data_creacio', models.DateTimeField(auto_now=True)),
                ('data_error', models.DateTimeField()),
                ('estat', models.CharField(choices=[('Operatiu', 'Operatiu'), ('Inoperatiu', 'Inoperatiu')], default='Operatiu', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Servei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomServei', models.CharField(max_length=50)),
                ('criticitat', models.CharField(choices=[('Baixa', 'Baixa'), ('Mitjana', 'Mitjana'), ('Alta', 'Alta')], default='Baixa', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='actiu',
            name='servei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pla.Servei'),
        ),
    ]
