# Generated by Django 2.0.2 on 2018-02-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(max_length=250)),
                ('actiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pla.Actiu')),
                ('servei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pla.Servei')),
            ],
        ),
    ]
