# Generated by Django 2.0.2 on 2018-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pla', '0003_auto_20180209_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiu',
            name='data_creacio',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='actiu',
            name='data_error',
            field=models.DateTimeField(null=True),
        ),
    ]
