# Generated by Django 2.0.2 on 2018-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pla', '0004_auto_20180209_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiu',
            name='data_error',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
