# Generated by Django 2.0.2 on 2018-02-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pla', '0007_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiu',
            name='ip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pla.Ips'),
            preserve_default=False,
        ),
    ]
