# Generated by Django 2.0.2 on 2018-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pla', '0008_actiu_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiu',
            name='ip',
        ),
        migrations.AddField(
            model_name='actiu',
            name='ip',
            field=models.ManyToManyField(to='pla.Ips'),
        ),
    ]
