# Generated by Django 2.2.1 on 2019-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pla', '0009_auto_20180220_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
